// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Runestone.FSharp")>]
[<assembly: AssemblyProductAttribute("Runestone.FSharp")>]
[<assembly: AssemblyDescriptionAttribute("A tool for analyzing Portable Executable files.")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: GuidAttribute("b7390b74-05e0-4eef-9739-88c21fe7b6f9")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Runestone.FSharp"
    let [<Literal>] AssemblyProduct = "Runestone.FSharp"
    let [<Literal>] AssemblyDescription = "A tool for analyzing Portable Executable files."
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] Guid = "b7390b74-05e0-4eef-9739-88c21fe7b6f9"
